name: dotnet-sdk
version: 7.0.405
summary: Cross-Platform .NET Core SDK
description: |
  .NET Core SDK. https://dot.net/core.

architectures:
  - build-on: amd64
    run-on: amd64

grade: stable
confinement: classic
base: core20

parts:
  dotnet-sdk:
      plugin: dump
      source: https://download.visualstudio.microsoft.com/download/pr/5202b091-2406-445c-b40a-68a5b97c882b/b509f2a7a0eb61aea145b990b40b6d5b/dotnet-sdk-7.0.405-linux-x64.tar.gz
      source-checksum: sha512/6cdf82af56f920c87315209f5b5166126e97b13b6d715b6507ddbc9a2eb618f812e43686b79de810ae6a21e0fb5a8e04d68a004f00a07533c8b664f9c889b5b0
      stage-packages:
      - libicu66
      - libgcc1
      - libstdc++6
      - libssl1.1
      - libcurl4
      - libgssapi-krb5-2
      - zlib1g
      - lldb
      - libunwind8
      - libtinfo5
      - liblttng-ust0
      - liburcu6

  runtime-wrapper:
      plugin: dump
      source: .

apps:
  dotnet:
    command: dotnet


