name: dotnet-sdk
version: 6.0.418
summary: Cross-Platform .NET Core SDK
description: |
  .NET Core SDK. https://dot.net/core.

architectures:
  - build-on: amd64
    run-on: amd64

grade: stable
confinement: classic
base: core20

parts:
  dotnet-sdk:
      plugin: dump
      source: https://download.visualstudio.microsoft.com/download/pr/01292c7c-a1ec-4957-90fc-3f6a2a1e5edc/025e84c4d9bd4aeb003d4f07b42e9159/dotnet-sdk-6.0.418-linux-x64.tar.gz
      source-checksum: sha512/24d705157ae51ed5ec5ff267c76474d2ff71b0e56693f700de456321f15212a7791291b95770522a976434f5220e5c03b042f41755a0b6e9854abf73cd51e299
      stage-packages:      
      - libicu66
      - libgcc1
      - libstdc++6
      - libssl1.1
      - libcurl4
      - libgssapi-krb5-2
      - zlib1g
      - lldb
      - libunwind8
      - libtinfo5
      - liblttng-ust0
      - liburcu6

  runtime-wrapper:
      plugin: dump
      source: .

apps:
  dotnet:
    command: dotnet

